### ISSUE TITLE
Cannot run with xUnit async tests

### ISSUE THREAD

**Issue by togakangaroo** [approvals/ApprovalTests.Net#1]
Writing xUnit tests in the format

``` C#
[Fact]
public async Task MyAsyncUnitTest()
{
    // ... setup code here ...
    var result = await CallMyAsyncApi(...);
    // ... assertions here ...
}
```

[as denoted in Brad Wilson's blog](http://bradwilson.typepad.com/blog/2012/01/xunit19.html)

fails with the error

failed: System.Exception : Approvals is not set up to use your test framework.
It currently supports [xUnit.net]
To add one use ApprovalTests.StackTraceParsers.StackTraceParser.AddParser() method to add implementation of ApprovalTests.StackTraceParsers.IStackTraceParser with support for your testing framework.

**Comment by goblinfactory** [comment]
Why is this closed? Just started working with another enterprise client using Xunit, and all their code and test code is async. I don't see async tests as an edge case, I see non async code as edge cases. Regardless,   don't understand why this was marked as closed? As far as I can tell It's still broken, and was never fixed. 

This should be left as an open known bug, so that if anyone is considering using ApprovalTests they can make an informed decision when working on a project.

**Comment by SimonCropp** [comment]
@goblinfactory can u submit a PR with a failing unit test

**Comment by goblinfactory** [comment]
Hi @SimonCropp sure can! :) 
does this mean you want to take a fresh look?
All the comments above are all still valid though. It's a "still open" issue, I was just saying this shouldnt be closed because all the original issues raised, and code samples are still valid, they all still fail.

In case I get caught in a meeting for a few days, my workaround so far has been to write my test asnon async and wrap in async task so that i'm genuinely testing the async flow;

```csharp
// this is the work around, not the bug :)
[UseReporter(typeof(DiffReporter)]
public void SomeFooTestTestingSomeAsyncThing()
{
  var json = Task.Run(async () => 
   {
     using(var client = _api._CreateClient()) 
     {
       ... do some async stuff
      var content = await _api.ReadContentAsStringAsync();
       return content;
     } 
      ApprovalTests.VerifyJson(json);
   }

}

```

**Comment by goblinfactory** [comment]
@SimonCropp by PR with failing test, do you simply mean  an async version of this test?

https://github.com/approvals/ApprovalTests.Net/blob/master/ApprovalTests.Xunit2/CompatibilityWithXunit1Test.cs

I'm not at my desk, so can't do this now. I can do it in the morning on the train on way to work, shouldn't take me more than a few minutes. 
Will be super happy to get this working!

Cheers,

Alan
