### ISSUE TITLE
Better Reporter Names

### ISSUE THREAD

**Issue by isidore** [approvals/ApprovalTests.Net#145]
It was brought to my attention that the Reporters aren't very discoverable. Suggest renaming to start all with the word Report

This is large, so wanted feedback before I do.

Note: I will maintain backwards compatibility for all existing names.

Suggestions

 AllFailingTestsClipboardReporter ->  ReportAllFailingTestsToClipboard  
 AppConfigReporter -> ReportWithReporterInAppConfig
 AppVeyorReporter -> ReportSilentlyWhenOnAppVeyor
 AraxisMergeReporter -> ReportWithAraxisMerge
 AssertReporter ------> no change (base class)?
 BambooReporter -> ReportSilentlyWhenOnBamboo
 BeyondCompare3Reporter -> ReportWithBeyondCompare3
 BeyondCompare4Reporter.cs -> ReportWithBeyondCompare4
 BeyondCompareReporter.cs -> ReportWithBeyondCompare
 ClipboardReporter.cs -> ReportToClipboard
 CodeCompareReporter.cs -> ReportWithCodeCompare
 CruiseControlNetReporter.cs -> ReportSilentlyWhenOnCruiseControlNet
 DefaultFrontLoaderReporter.cs --------------> no change ?
 DiffReporter.cs -> ReportWithDiffTool
 FileLauncherReporter -> ReportByLaunchingFile
 FileLauncherWithDelayReporter -> ReportByLaunchingFileWithSmallDelay
 FirstWorkingReporter.cs ------------------> no change?
 FrameworkAssertReporter.cs -> ReportWithAssertEquals
 GenericDiffReporter -----------------> no change (base class)
 GoContinuousDeliveryReporter -> ReportSilentlyOnGoContinuousDelivery
 ImageReporter -> ReportWithImageTools
 IntroductionReporter ---------------> no change (not meant to be used on purpose)
 JenkinsReporter -> ReportSilentlyOnJenkins
 KDiffReporter.cs -> ReportWithKDiff
 MightyMooseAutoTestReporter.cs -> ReportSilentlyWhenUsingMightMoose
 MsTestReporter.cs -> ReportWithMsTestAssertEquals
 MultiReporter.cs -----------> no change ?
 MyGetReporter.cs -> ReportSilentlyOnMyGet
 NCrunchReporter.cs -> ReportSilentlyWhenUsingNCrunch
 NUnitReporter.cs -> ReportWithNUnitAssertEquals
 NotepadLauncher -> ReportWithNotepad
 P4MergeImageReporter -> ReportWithP4MergeForImages
 P4MergeReporter.cs ->  ReportWithP4Merge
 P4MergeTextReporter.cs -> ReportWithP4MergeForText
 PowershellClipboardReporter.cs -> ReportToPowershellClipboard
 QuietReporter.cs -> ReportSilently
 TeamCityReporter.cs -> ReportSilentlyWhenUsingTeamCity
 TfsReporter -> ReportSilentlyWhenUsingTfs
 TfsVnextReporter.cs -> ReportSilentlyWhenUsingTfsVnext
 TortoiseComboImageReporter.cs -> ReportWithTortoiseDiffForImagesOrFileLauncher
 TortoiseDiffReporter.cs -> ReportWithTortoiseDiff
 TortoiseImageDiffReporter.cs -> ReportWithTortoiseDiffForImages
 TortoiseTextDiffReporter.cs -> ReportWithTortoiseDiffForText
 VisualStudioReporter.cs -> ReportWithVisualStudio
 WinMergeReporter.cs -> ReportWithWinMerge
 XUnit2Reporter.cs -> ReportWithXUnit2AssertEquals
 XUnitReporter.cs -> ReportWithXUnitAssertEquals

What do you think?

**Comment by treymack** [comment]
Are they all in the `ApprovalTests.Reporters` namespace? If so, intellisense can kick in with the `.` after the namespace.

I dig the more intention-revealing names, ex:
`CruiseControlNetReporter.cs -> ReportSilentlyWhenOnCruiseControlNet`

**Comment by JayBazuzi** [comment]
I like it.

Today, I type `Reporter` and let Intellisense find it, but what you are proposing would be even better.

Take a step further and make these the attributes, so I can do:

`[ReportWithKDiff]`

This will make intellisense work better, because `typeof(...)` can take anything, but `[...` will only offer Attributes.

**Comment by jamesrcounts** [comment]
Ugh, sorry.  The proposed new names are just ugly to me.  @treymack rather than renaming the reporter I'd rather just create a `SilentReporters` namespace.

I think the existing reporters namespace is discoverable enough.  If intellisense can find them by typing "Reporter", what difference does it make "how" intellisense finds it?  Having a reporters namespace where everything is named `ApprovalTests.Reporters.ReportWithX` is redundant.  Starting everything everything with the same prefix actually makes it harder for intellisense.  Right now I can type `BC` when I want to find the `BeyondCompareReporter`.  In the future it will be `RBC`.  Sure, it will just be one more keystroke, but its not an improvement.

The main problem with discoverability is that the user needs to know about reporters at all. 99% of users will be happy with just `DiffReporter` it should be loaded by default when no reporter is specified.  

Advanced users would be better served  by some documentation rather than giving everything names that are 4x as long.

Sorry to be the party pooper.

**Comment by Ackara** [comment]
I agree with @jamesrcounts, and to add to his point the Report* convention makes the classes sound like method names. I think seasoned .NET devs except their classes to be nouns not verbs.

**Comment by isidore** [comment]
I've now seen a few user tests and they don't seem to type the 'Reporter'
or have any way to know they show. This kills a lot of discoverability.  :-|

Llewellyn Falco
www.approvaltests.com

**Comment by SimonCropp** [comment]
given the recent diffengine changes this no longer makes sense
