### ISSUE TITLE
approved.txt and received.txt are swapped in Code Compare diff

### ISSUE THREAD

**Issue by thomaslevesque** [approvals/ApprovalTests.Net#160]
`(name).approved.txt` should be on the left ("base" file) and `(name).received.txt` on the right. Otherwise, removed APIs appear as added in the diff, and added APIs appear as removed, which is quite confusing. I haven't tested with other diff tools, but I suspect many have the same issue.

**Comment by isidore** [comment]
this is on purpose so you can copy results to the approved file

**Comment by isidore** [comment]
possible in code compare but many diff only copy left to right

**Comment by thomaslevesque** [comment]
Ah, I see... Still, it's pretty confusing. Thanks for the explanation anyway.

**Comment by blairconrad** [comment]
@isidore, would you be open to an option that could be supplied so diffs are launched with "approved" on the left?

**Comment by isidore** [comment]
it's hard to pass in options because you are only stating class type in the
attributes but here's a version with the sides swapped you can use


using ApprovalUtilities.Utilities;


public class RightSideCodeCompareReporter : GenericDiffReporter
{
private readonly static string PATH =
DotNet4Utilities.GetPathInProgramFilesX86(@"Devart" +
System.IO.Path.DirectorySeparatorChar + "Code Compare" +
System.IO.Path.DirectorySeparatorChar + "CodeCompare.exe");
public readonly static CodeCompareReporter INSTANCE = new
CodeCompareReporter();
public CodeCompareReporter()
: base(
PATH,
"/ENVIRONMENT=visualstudio \"{1}\" \"{0}\"",
"Could not find DevArt Code Compare at {0}.".FormatWith(PATH))
{
}
}


Llewellyn Falco
www.approvaltests.com

**Comment by blairconrad** [comment]
Thanks for that, @isidore.

**Comment by blairconrad** [comment]
Oh, not to push things, but one thing that @thomaslevesque and I had discussed offline was the possibility of reacting to an environment variable to choose which side "approved" and "received" go on.

Sorry. I'm done. Thanks again!
