### ISSUE TITLE
Renaming test still creates old and new approval files

### ISSUE THREAD

**Issue by jawn** [approvals/ApprovalTests.Net#216]
## Steps
1. Create a new Class library using .NET full framework, using Visual Studio 2017 version 15.6.4.
2. Install-Package ApprovalTests
3. Install-Package xunit
4. Replace code with 

```
using System;
using ApprovalTests;
using ApprovalTests.Reporters;
using Xunit;

namespace ClassLibrary1
{
    public class Class1
    {
        [Fact]
        [UseReporter(typeof(DiffReporter))]
        public void Name1()
        {
            var names = new[] { "Llewellyn", "James", "Dan", "Jason", "Katrina" };
            Array.Sort(names);
            Approvals.VerifyAll(names, "");
        }
    }
}
```

5. Run tests
6. Show hidden files

Approved & received files are created as expected:

![image](https://user-images.githubusercontent.com/1705112/38253026-e47d77b4-3755-11e8-8526-02cfd98a84aa.png)

7. Rename the test method from `Name1()` to `Name2()`.
8. Rebuild solution.
9. Delete all .approved.* and .received.* files.

Run all tests.

## Expected result
Approved and received file is created for the new test name.

## Actual result
Approved and received file are created for the new test name (good).

Approved and received file are also created for the old test name (unexpected).

## Notes

Same applies if I do a clean solution first and delete the .suo file.
Using Resharper to run the tests.

**Comment by jawn** [comment]
I confirm the same issue when using `install-package xunit.runner.visualstudio` and the default test runner in Visual Studio.

**Comment by isidore** [comment]
This is expected behavior, 
Here's what's going on.

1) the rename function in resharper/vs doesn't rename the approvaltests
2) The clean solution doesn't delete the approvaltest files
3) when you run approvaltests, it creates an empty approvalfile if one doesn't exist, this is because most diff tools don't respond well to non-existing files

So when you rename, it's like creating a new test. The old .approved & .recieved files don't change or delete. Then when you run the 'new' test it's like the first time.

To fix this you can't do anything in approvaltests, you would need a resharper plugin.
